name: Docker
on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'README.md' # 忽略README.md修改触发
      - '.dockerignore' # 忽略.dockerignore修改触发
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md' # 忽略README.md修改触发
      - '.dockerignore' # 忽略.dockerignore修改触发
  workflow_dispatch: # 添加手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: 登录Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: 构建并推送
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/siliconflow-python:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/siliconflow-python:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
